### PR TITLE
Fix corrupted Parametric Stereo (PS) flag in downloaded .m3u8 videos

### PR DESCRIPTION
**Pull request by Type-Delta**
# What this PR does
- added --force-ffmpeg & --hls-use-mpegts options to properly handle some m3u8 streams 

# Explanation 
### Fix corrupted Parametric Stereo (PS) flag in downloaded videos
Corrupted PS flag was caused by `yt-dlp` copping audio stream directly from `aac (HE-AACv2)` stream
without converting it to stereo channels first which resulted in mono channel `aac (LC)`.

As pointed in #8: FFprobe (and FFmpeg) recognized `aac (HE-AACv2)` pattern in the downloaded videos
but because the PS flag wasn't being carried over from the original `.m3u8`, 
it noticed something was wrong hence, the error.

This is a big loss of data, since most players can read stereo data from `aac (HE-AACv2)`, 
but not from a loosely copied over `aac (LC)`, which only mono data can be retrieved.

The issue can now be solved by passing `--hls-use-mpegts` flag to Fastanime which will apply the fix.

# The Fixes
### Fix corrupted Parametric Stereo (PS) flag in downloaded videos
The fix is to tell `yt-dlp` to use FFmpeg instead of its build-in downloader which doesn't supports hls streams,
and force it use mpegts for the output container.

### CODE REVIEW

**Comment by Benex254** [comment]
Awesome thanks for sharing let me try out real quick. 
Ngl doubt i could have been able to figure this one out  :sweat_smile:

**Comment by Type-Delta** [comment]
Glad it helped 👍, let me know how it went for you!

**Comment by Type-Delta** [comment]
sure!

**Review by Benexl — APPROVED** [review]
Everything works, nicely and no ffprobe errors

**Pull request merged**
